@startuml
interface Iterable
interface Collection
abstract class AbstractCollection
interface Queue
class LinkedBlockingQueue
abstract class AbstractQueue
interface BlockingQueue


Iterable <|-- Collection
Collection <|.. AbstractCollection
Collection <|-- Queue
AbstractCollection <|-- AbstractQueue
Queue <|.. AbstractQueue
Queue<|-- BlockingQueue

AbstractQueue <|.. LinkedBlockingQueue
BlockingQueue <|.. LinkedBlockingQueue
Serializable <|.. LinkedBlockingQueue

AbstractQueue <|-- ArrayBlockingQueue
BlockingQueue <|.. ArrayBlockingQueue
Serializable <|.. ArrayBlockingQueue

AbstractQueue <|-- PriorityBlockingQueue
BlockingQueue <|.. PriorityBlockingQueue
Serializable <|.. PriorityBlockingQueue

AbstractQueue <|-- SynchronousQueue
BlockingQueue <|.. SynchronousQueue
Serializable <|.. SynchronousQueue

Iterable : iterator()
Queue : boolean add(E e)
Queue : boolean offer(E e)
Queue : E remove()
Queue : E poll()
Queue : E element()
Queue : E peek()


@enduml
